FROM mcr.microsoft.com/devcontainers/python:3.12

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    git git-lfs austin graphviz graphviz-dev libboost-all-dev libilmbase-dev \
    libopenexr-dev libpng-dev libtiff5-dev && \
    apt-get autoremove -y && \
    apt-get clean -y && \
    DEBIAN_FRONTEND=

USER vscode
RUN pipx install poetry && \
    poetry config virtualenvs.in-project true && \
    pip install imageio && \
    python -c "import imageio;imageio.plugins.freeimage.download()"